# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: joesharpcs/jgaming-service:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

