# Use root/example as user/password credentials
version: '3.1'

services:
  jgaming-api:
    image: joesharp/jgaming-api:latest
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  jgaming-ui:
    image: joesharp/jgaming-ui:latest
    ports:
      - "9080:80"

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

