# Use root/example as user/password credentials
version: '3.1'

services:
  jgaming-service:
    image: joesharpcs/jgaming-service:latest
    ports:
      - "8081:8081"
    environment:
      JGAMING_SERVICE_PORT: 8081
      REDIS_HOST: redis
      REDIS_PORT: 6379

  jgaming-ui:
    image: joesharpcs/jgaming-ui:latest
    ports:
      - "8000:8000"

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

