# Use root/example as user/password credentials
version: '3.1'

services:
  jgaming-api:
    image: joesharpcs/jgaming-api:latest
    ports:
      - "8081:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  jgaming-ui:
    image: joesharpcs/jgaming-ui:latest
    ports:
      - "8000:8000"

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

